{
 "title": "Weather",
 "description": "Weather data including Temperature, Pressure, Humidity for a particular place and a particular sensor ie Place = Baanfalang and sensor = Office01",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "site_name",
    "label": "Site Name",
    "query": {
     "query": "import \"influxdata/influxdb/schema\"\n\nschema.tagValues(\n    bucket: \"Weather\",\n    tag: \"site_name\",\n    predicate: (r) => r._measurement == \"Readings\" and r.device_type == \"weather\"\n)"
    }
   },
   {
    "name": "device_id",
    "label": "Device ID",
    "query": {
     "query": "import \"influxdata/influxdb/schema\"\n\nschema.tagValues(\n    bucket: \"Weather\",\n    tag: \"device_id\",\n    predicate: (r) => r._measurement == \"Readings\" and r.device_type == \"weather\" and r.site_name == \"${site_name}\"\n)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Current Temperature",
   "type": "gauge",
   "description": "Latest temperature reading from selected device",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Weather\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Readings\")\n  |> filter(fn: (r) => r[\"device_type\"] == \"weather\")\n  |> filter(fn: (r) => r[\"site_name\"] == \"${site_name}\")\n  |> filter(fn: (r) => r[\"device_id\"] =~ /^(${device_id:regex})$/)\n  |> filter(fn: (r) => r[\"_field\"] == \"temperature\")\n  |> last()\n  |> yield(name: \"current_temperature\")"
    }
   ]
  },
  {
   "title": "Temperature over time",
   "type": "timeseries",
   "description": "Temperature readings from selected weather devices",
   "gridPos": { "h": 6, "w": 21, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"Weather\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Readings\")\n  |> filter(fn: (r) => r[\"device_type\"] == \"weather\")\n  |> filter(fn: (r) => r[\"site_name\"] == \"${site_name}\")\n  |> filter(fn: (r) => r[\"device_id\"] =~ /^(${device_id:regex})$/)\n  |> filter(fn: (r) => r[\"_field\"] == \"temperature\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"temperature\")"
    }
   ]
  },
  {
   "title": "Current Humidity",
   "type": "gauge",
   "description": "Latest humidity reading from selected device",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Weather\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Readings\")\n  |> filter(fn: (r) => r[\"device_type\"] == \"weather\")\n  |> filter(fn: (r) => r[\"site_name\"] == \"${site_name}\")\n  |> filter(fn: (r) => r[\"device_id\"] =~ /^(${device_id:regex})$/)\n  |> filter(fn: (r) => r[\"_field\"] == \"humidity\")\n  |> last()\n  |> yield(name: \"current_humidity\")"
    }
   ]
  },
  {
   "title": "Humidity Over Time",
   "type": "timeseries",
   "description": "Humidity readings from selected weather devices",
   "gridPos": { "h": 5, "w": 21, "x": 3, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"Weather\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Readings\")\n  |> filter(fn: (r) => r[\"device_type\"] == \"weather\")\n  |> filter(fn: (r) => r[\"site_name\"] == \"${site_name}\")\n  |> filter(fn: (r) => r[\"device_id\"] =~ /^(${device_id:regex})$/)\n  |> filter(fn: (r) => r[\"_field\"] == \"humidity\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"humidity\")"
    }
   ]
  },
  {
   "title": "Current Pressure",
   "type": "gauge",
   "description": "Latest atmospheric pressure reading from selected device",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Weather\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Readings\")\n  |> filter(fn: (r) => r[\"device_type\"] == \"weather\")\n  |> filter(fn: (r) => r[\"site_name\"] == \"${site_name}\")\n  |> filter(fn: (r) => r[\"device_id\"] =~ /^(${device_id:regex})$/)\n  |> filter(fn: (r) => r[\"_field\"] == \"pressure\")\n  |> last()\n  |> yield(name: \"current_pressure\")"
    }
   ]
  },
  {
   "title": "Atmospheric Pressure Over Time",
   "type": "timeseries",
   "description": "Pressure readings from selected weather devices",
   "gridPos": { "h": 5, "w": 21, "x": 3, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "targets": [
    {
     "query": "from(bucket: \"Weather\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Readings\")\n  |> filter(fn: (r) => r[\"device_type\"] == \"weather\")\n  |> filter(fn: (r) => r[\"site_name\"] == \"${site_name}\")\n  |> filter(fn: (r) => r[\"device_id\"] =~ /^(${device_id:regex})$/)\n  |> filter(fn: (r) => r[\"_field\"] == \"pressure\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"pressure\")"
    }
   ]
  },
  {
   "title": "Current Light Level",
   "type": "gauge",
   "description": "Latest light intensity reading from selected device\n",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "lumens" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Weather\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Readings\")\n  |> filter(fn: (r) => r[\"device_type\"] == \"weather\")\n  |> filter(fn: (r) => r[\"site_name\"] == \"${site_name}\")\n  |> filter(fn: (r) => r[\"device_id\"] =~ /^(${device_id:regex})$/)\n  |> filter(fn: (r) => r[\"_field\"] == \"lux\")\n  |> last()\n  |> yield(name: \"current_lux\")"
    }
   ]
  },
  {
   "title": "Light Level Over Time",
   "type": "timeseries",
   "description": "Light intensity readings from selected weather devices",
   "gridPos": { "h": 5, "w": 21, "x": 3, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "lumens" } },
   "targets": [
    {
     "query": "from(bucket: \"Weather\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Readings\")\n  |> filter(fn: (r) => r[\"device_type\"] == \"weather\")\n  |> filter(fn: (r) => r[\"site_name\"] == \"${site_name}\")\n  |> filter(fn: (r) => r[\"device_id\"] =~ /^(${device_id:regex})$/)\n  |> filter(fn: (r) => r[\"_field\"] == \"lux\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"lux\")"
    }
   ]
  }
 ]
}