#ifndef PROJECT_VERSION_H
#define PROJECT_VERSION_H

// This file is auto-generated by CMake from project_version.h.in
// Do not edit manually - version is controlled by CMakeLists.txt VERSION field

#define PROJECT_VERSION "0.0.1"

#endif // PROJECT_VERSION_H
